title: "SweepRSS"
app_name: "SweepRSS"
bundle_id: "jp.hackwork.sweeprss"
version: "0.3.2"
description: "SweepRSS - cross-platform RSS reader"

contents:
  - x: 192
    y: 344
    type: "file"
    path: "SweepRSS.app"
  - x: 448
    y: 344
    type: "link"
    path: "/Applications"
